name: server:build_and_lint

on:
  push:
    branches: [master]
    # paths:
    #   - "server/**"
  pull_request:
    branches: [master]
    # paths:
    #   - "server/**"

jobs:
  build:
    name: build-and-lint-server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: cd server && yarn install
      - run: cd server && yarn build
      - run: cd server && yarn lint
      - run: cd server && yarn format
